"""init

Revision ID: 4cf1364f77c9
Revises: 6fd7510dd57a
Create Date: 2026-06-29 14:48:56.650359

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4cf1364f77c9'
down_revision: Union[str, None] = '6fd7510dd57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
